### ISSUE TITLE
How do you repeat it? Continuous loop? 

### ISSUE THREAD

**Issue by amityweb** [mrvautin/typewrite#6]
How do you repeat it? Continuous loop?

**Comment by Mineslu** [comment]
I need the same

**Comment by mrvautin** [comment]
Added: 404c548839a5a7226009325520e4eab147460ab4

**Comment by Raghwendra-Dey** [comment]
Hey!
do continuous repeats all the actions.
If i want to type something then remove all the text and then again retype and loop is this correct:
```javascript
<script>
  $(document).ready(function () {
    $("#typewriteText").typewrite({
      continuous: true,
      actions: [{ type: "{{site.typewrite-text}}" },
        { delay: 4000 },
        {remove: {num: 48, type: 'stepped'}},
        { delay: 1000 },
      ]
    });
  });
</script>
```
But when i run this, i am not getting the desired effect, i.e after one cycle it just stops, and that block paragraph element starts oscillating, any solutions for that?
(`num:48` because the whole text is of 48 characters)
